apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: amogus-admin-bot
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        targetPort: 1337
  healthcheck:
    enabled: false
  allowConnectTo:
    - amogus
  image: eu.gcr.io/imaginaryctf-2023/amogus-admin-bot-challenge:18b611bf76565de04221f88848148dcd8625b668b3b8182dd26d1f33ebbff68c
