apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: lcode
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/lcode-challenge:07157b071e97a65c8fe535311feea11459a4b2425c6a1157ba34598b5e939d80
