apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: sanitized-revenge
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 3000
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/sanitized-revenge-challenge:0d9c2d61e282fc50fe7baafff09712b50076a0039220c9f998c3d5360431d8d0
