apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: login
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 80
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/login-challenge:5f3b0f802ee54623f5cd3fbb52d9b2fcef1f27a141de636763d86b79cae16471
