apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: sanitized
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 3000
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/sanitized-challenge:b7dc4c3c76baf0ca2964680b06fcf6c19f65c6609068e72a95b3bc88d2d78654
