apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: elliptic
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/elliptic-challenge:5c89535f586ccbc34fd9585bd03ed0347e6751a930ef5c6f764210821cd13859
