apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: perfect-picture
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 5000
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/perfect-picture-challenge:a02f24a399a57629dc8d41d07942b89e3eca049910bcb375b1f5efa35faa04b6
