apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: roks
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 80
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/roks-challenge:9ff26474fcd97faaefdc80798d4651d78fc11e4ded44cf5c7d3829e69a868e97
