apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: form
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/form-challenge:f8dd5e8121328c20975dd24e9ec5f62654d6e030e9d1e554ccfe6c368d1a174d
