apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: signer
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/signer-challenge:d6275a1978f8228b9b5b9fab250742ed23e7818579c7ba3ffd1f263850526d39
