apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: window-of-opportunity
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/window-of-opportunity-challenge:b69e2de15fb89738f586c88e9a260e92b19bd78506a2e815d3814edb8dd1a3f4
